import crypto from 'node:crypto';
import nodemailer from 'nodemailer';
import logger from './logger.js';

/**
 * OTP (One-Time Password) utility for Email and SMS
 *
 * Unlike TOTP (time-based, shared secret), these are random codes
 * generated by the server and delivered to the user via a side channel.
 *
 * Security properties:
 *   - Random 6-digit code (cryptographically secure)
 *   - Short TTL (5 minutes for email, 3 minutes for SMS)
 *   - One-time use (consumed after verification)
 *   - Rate limited (max attempts tracked in model)
 *   - SHA-256 hashed in database (like refresh tokens)
 */

/**
 * Generate a random numeric OTP
 * @param {number} digits - Code length (default: 6)
 * @returns {string} Zero-padded numeric code
 */
const generateOTP = (digits = 6) => {
  const max = Math.pow(10, digits);
  const randomInt = crypto.randomInt(0, max);
  return randomInt.toString().padStart(digits, '0');
};

// ─── Email Transport ───

let transporter = null;

/**
 * Get or create email transporter
 * Lazy initialization — created on first use
 */
const getTransporter = () => {
  if (transporter) return transporter;

  transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.ethereal.email',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  return transporter;
};

/**
 * Send OTP via email
 *
 * In development: uses Ethereal (fake SMTP — emails visible at ethereal.email)
 * In production: use real SMTP (SendGrid, AWS SES, Mailgun, etc.)
 *
 * @param {string} to - Recipient email
 * @param {string} code - OTP code
 * @returns {Promise<Object>} Nodemailer send result
 */
const sendEmailOTP = async (to, code) => {
  const transport = getTransporter();

  const info = await transport.sendMail({
    from: process.env.EMAIL_FROM || 'noreply@authguide.dev',
    to,
    subject: `Your verification code: ${code}`,
    text: `Your one-time verification code is: ${code}\n\nThis code expires in 5 minutes.\nIf you did not request this code, please ignore this email.`,
    html: `
      <div style="font-family: sans-serif; max-width: 400px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #333;">Verification Code</h2>
        <p style="color: #666;">Your one-time verification code is:</p>
        <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; text-align: center; margin: 16px 0;">
          <span style="font-size: 32px; font-weight: bold; letter-spacing: 8px; color: #2563eb;">${code}</span>
        </div>
        <p style="color: #999; font-size: 14px;">This code expires in 5 minutes.</p>
        <p style="color: #999; font-size: 14px;">If you did not request this code, please ignore this email.</p>
      </div>
    `,
  });

  // In dev with Ethereal, log the preview URL
  if (process.env.SMTP_HOST?.includes('ethereal')) {
    const previewUrl = nodemailer.getTestMessageUrl(info);
    logger.info({ msg: 'Email OTP sent (Ethereal preview)', to, previewUrl });
  } else {
    logger.info({ msg: 'Email OTP sent', to, messageId: info.messageId });
  }

  return info;
};

/**
 * Send OTP via SMS (Twilio)
 *
 * In development: logs the code to console (no Twilio needed)
 * In production: set TWILIO_* env vars
 *
 * @param {string} phoneNumber - Recipient phone (E.164 format: +1234567890)
 * @param {string} code - OTP code
 */
const sendSMSOTP = async (phoneNumber, code) => {
  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken = process.env.TWILIO_AUTH_TOKEN;
  const fromNumber = process.env.TWILIO_PHONE_NUMBER;

  if (!accountSid || !authToken) {
    // Dev mode — just log it
    logger.info({
      msg: 'SMS OTP (dev mode — no Twilio configured)',
      phoneNumber,
      code,
      note: 'Set TWILIO_* env vars for real SMS',
    });
    return { sid: 'dev-mode', to: phoneNumber };
  }

  // Dynamic import — only load Twilio SDK when actually needed
  // This keeps the package optional (not in package.json)
  const { default: twilio } = await import('twilio');
  const client = twilio(accountSid, authToken);

  const message = await client.messages.create({
    body: `Your verification code is: ${code}. It expires in 3 minutes.`,
    from: fromNumber,
    to: phoneNumber,
  });

  logger.info({ msg: 'SMS OTP sent', phoneNumber, sid: message.sid });
  return message;
};

export { generateOTP, sendEmailOTP, sendSMSOTP };
