const PUBLIC_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PUBLIC_KEY: 'INVALID_PUBLIC_KEY',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
};

const PRIVATE_ERROR_CODES = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
};

const DEFAULT_ERROR_CODE = 'UNKNOWN_ERROR';

const DEFAULT_ERROR_MESSAGE = 'We did not expect this. Please try again later.';

export { PUBLIC_ERROR_CODES, PRIVATE_ERROR_CODES, DEFAULT_ERROR_CODE, DEFAULT_ERROR_MESSAGE };
